-- CLOSE-04 only: extend append-only Stock Central movement vocabulary.
-- NOT executed by this change. Production migration remains explicitly out of scope.
ALTER TABLE stock_movement_groups
  MODIFY COLUMN movement_type ENUM(
    'RECEPTION','VENTE','RESERVATION_CLIENT','LIBERATION_RESERVATION_CLIENT',
    'RESERVATION_EVENEMENT','LIBERATION_RESERVATION_EVENEMENT','SORTIE_EVENEMENT',
    'RETOUR_EVENEMENT','CADEAU','ECHANTILLON','PERTE_CASSE','CORRECTION_INVENTAIRE',
    'MISE_EN_DEPOT','RETOUR_DE_DEPOT','OUVERTURE_BOITE','ENTREE_TRANSIT',
    'RECEPTION_TRANSIT','ASSEMBLAGE_COMPOSITE','DESASSEMBLAGE_COMPOSITE',
    'TRANSFERT_INTERNE','ANNULATION_VENTE'
  ) NOT NULL;
--> statement-breakpoint

ALTER TABLE stock_movements
  MODIFY COLUMN movement_type ENUM(
    'RECEPTION','VENTE','RESERVATION_CLIENT','LIBERATION_RESERVATION_CLIENT',
    'RESERVATION_EVENEMENT','LIBERATION_RESERVATION_EVENEMENT','SORTIE_EVENEMENT',
    'RETOUR_EVENEMENT','CADEAU','ECHANTILLON','PERTE_CASSE','CORRECTION_INVENTAIRE',
    'MISE_EN_DEPOT','RETOUR_DE_DEPOT','OUVERTURE_BOITE','ENTREE_TRANSIT',
    'RECEPTION_TRANSIT','ASSEMBLAGE_COMPOSITE','DESASSEMBLAGE_COMPOSITE',
    'TRANSFERT_INTERNE','ANNULATION_VENTE'
  ) NOT NULL;
