import React, { useCallback, useEffect, useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { API_URL } from "@/config";

const summaryLabels: Record<string,string> = { activeIdentities:"Identités actives",physicalStockUnits:"Unités physiques",availableStockUnits:"Disponibles",reservedClient:"Réservé client",reservedEvent:"Réservé événement",atEvent:"À l’événement",deposit:"En dépôt",transit:"En transit",zeroPositions:"Positions zéro",inconsistentIdentities:"À vérifier",openPurchaseOrders:"PO ouverts" };
const alertLabels: Record<string,string> = { RECONCILIATION_ERROR:"Projections incohérentes",OUT_OF_STOCK:"Rupture",LOW_STOCK:"Stock bas",FULLY_RESERVED:"Entièrement réservé",LEGACY_UNKNOWN_EXPOSURE:"Provenance historique inconnue",DORMANT:"Stock dormant",OVERDUE_PO:"PO en retard" };
export const historyLabel=(row:any)=>row.historySufficient?(row.dormant?"Dormant":"Historique suffisant"):"Historique insuffisant — aucune conclusion de dormance";

export function MonitoringSummary({data}:{data:any}) { return <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">{Object.entries(summaryLabels).map(([key,label])=><div key={key} className={`rounded-xl border p-3 ${key==="inconsistentIdentities"&&data.summary[key]?"border-red-400 bg-red-50":"bg-white"}`}><div className="text-xs text-muted-foreground">{label}</div><div className="text-2xl font-bold tabular-nums">{data.summary[key]??0}</div></div>)}</div><p className="text-xs text-muted-foreground">{data.unitWarning}</p></>; }
export function AttentionQueue({rows}:{rows:any[]}) { return rows.length?<div className="grid gap-2">{rows.map((row,index)=><div key={`${row.type}-${row.label}-${index}`} className={`rounded-lg border p-3 ${row.severity==="CRITICAL"?"border-red-500 bg-red-50":row.severity==="ATTENTION"?"border-amber-400 bg-amber-50":"bg-white"}`}><strong>{alertLabels[row.type]||row.type}</strong> · {row.label}{row.availableNow!=null&&<span> · disponible {row.availableNow}</span>}</div>)}</div>:<p className="rounded-lg border border-dashed p-5 text-muted-foreground">Aucune exception avec les filtres actuels.</p>; }
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}) { return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[800px] text-sm"><thead className="bg-muted/60"><tr>{headers.map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((cells,i)=><tr key={i}>{cells.map((cell,j)=><td key={j} className="p-3">{cell}</td>)}</tr>)}</tbody></table></div>; }

export default function StockMonitoring() {
  const [data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const [filters,setFilters]=useState<any>({search:"",alertType:"",locationId:"",poStatus:"",movementType:"",offset:0});
  const load=useCallback(async()=>{setBusy(true);setError("");const params=new URLSearchParams({limit:"25",offset:String(filters.offset)});for(const [k,v] of Object.entries(filters))if(k!=="offset"&&v)params.set(k,String(v));try{const response=await fetch(`${API_URL}/api/admin/stock/monitoring?${params}`,{headers:{"x-cms-token":sessionStorage.getItem("cms_token")||""}});const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);}catch(reason){setError(String((reason as Error).message||reason));}finally{setBusy(false);}},[filters]);
  useEffect(()=>{load();},[load]); const update=(key:string,value:string)=>setFilters((current:any)=>({...current,[key]:value,offset:0}));
  return <section className="space-y-5 rounded-2xl border bg-slate-50/70 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-bold">Pilotage & monitoring</h2><p className="text-sm text-muted-foreground">Lecture seule des faits M4–M8 réconciliés.</p></div><button onClick={load} disabled={busy} className="inline-flex items-center gap-2 rounded border bg-white px-3 py-2"><RefreshCw size={16}/>{busy?"Actualisation…":"Actualiser"}</button></div>
  <div className="grid gap-2 md:grid-cols-5"><input aria-label="Filtre produit" value={filters.search} onChange={e=>update("search",e.target.value)} placeholder="SKU / produit" className="rounded border p-2"/><select aria-label="Filtre alerte" value={filters.alertType} onChange={e=>update("alertType",e.target.value)} className="rounded border p-2"><option value="">Toutes alertes</option>{Object.entries(alertLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Filtre lieu" value={filters.locationId} onChange={e=>update("locationId",e.target.value)} className="rounded border p-2"><option value="">Tous lieux</option>{data?.locations?.map((l:any)=><option key={l.locationId} value={l.locationId}>{l.code} · {l.name}</option>)}</select><select aria-label="Filtre PO" value={filters.poStatus} onChange={e=>update("poStatus",e.target.value)} className="rounded border p-2"><option value="">Tous PO</option><option>ORDERED</option><option>PARTIALLY_RECEIVED</option></select><select aria-label="Filtre mouvement" value={filters.movementType} onChange={e=>update("movementType",e.target.value)} className="rounded border p-2"><option value="">Tous mouvements</option>{["RECEPTION","VENTE","RESERVATION_CLIENT","RESERVATION_EVENEMENT","MISE_EN_DEPOT","SORTIE_EVENEMENT","RETOUR_EVENEMENT","CORRECTION_INVENTAIRE"].map(v=><option key={v}>{v}</option>)}</select></div>
  {error&&<div role="alert" className="rounded border border-red-400 bg-red-50 p-3"><AlertTriangle className="mr-2 inline"/>{error}</div>}{data&&<><MonitoringSummary data={data}/><div><h3 className="mb-2 text-lg font-bold">Attention prioritaire</h3><AttentionQueue rows={data.alerts.rows}/></div>
  <div><h3 className="mb-2 text-lg font-bold">Vendre maintenant</h3><Table headers={["Produit","Identité","Disponible","Physique","Dernier mouvement","État"]} rows={data.commercial.rows.map((r:any)=>[`${r.sku} · ${r.label}`,`${r.type}${r.type==="Pack"?`(${r.packSize})`:""}`,r.availableNow,r.physicalUnits,r.lastMovementAt?new Date(r.lastMovementAt).toLocaleDateString("fr-CA"):"Aucun observé",r.reconciled?historyLabel(r):"Stock à vérifier — projections incohérentes"])}/></div>
  <div><h3 className="mb-2 text-lg font-bold">Dormance / long tail</h3><p className="mb-2 text-xs text-muted-foreground">{data.historyPolicy}</p><Table headers={["Identité","Disponible","Dernière vente","Ventes 30/60/90j","Conclusion"]} rows={data.dormant.rows.map((r:any)=>[`${r.sku} · ${r.type}`,r.availableNow,r.lastSaleAt?new Date(r.lastSaleAt).toLocaleDateString("fr-CA"):"Aucune observée",`${r.sold30}/${r.sold60}/${r.sold90}`,historyLabel(r)])}/></div>
  <div><h3 className="mb-2 text-lg font-bold">Lieux</h3><Table headers={["Lieu","Positions","Physique","Disponible","Réservé","Événement / dépôt / transit","Alerte"]} rows={data.locations.map((r:any)=>[`${r.code} · ${r.name}`,r.activePositions,r.physicalUnits,r.availableNow,r.buckets.reservedClient+r.buckets.reservedEvent,`${r.buckets.atEvent} / ${r.buckets.deposit} / ${r.buckets.transit}`,r.inconsistentIdentities?`${r.inconsistentIdentities} incohérente(s)`:r.legacyUnknownExposure?"Legacy unknown":"—"])}/></div>
  <div><h3 className="mb-2 text-lg font-bold">Lots / âge de provenance</h3><Table headers={["Lot","Identité","Fournisseur / réception","Lieu","Restant","Âge"]} rows={data.lots.rows.map((r:any)=>[r.originKind==="LEGACY_UNKNOWN"?"Provenance inconnue":r.lotCode,`${r.sku} · ${r.type}`,r.receiptCode?`${r.supplierName} · ${r.receiptCode}`:"Non documenté",r.locationCode,r.physicalUnits,r.lotAgeDays==null?"Inconnu":`${r.lotAgeDays} j${r.lotAgeDays>=data.thresholds.oldLotDays?" · ancien":""}`])}/></div>
  <div><h3 className="mb-2 text-lg font-bold">Achats attendus</h3><Table headers={["PO","Fournisseur","Statut","Commandé / reçu / restant","Attendu","État"]} rows={data.purchasing.rows.map((r:any)=>[r.purchaseOrderCode,r.supplierName,r.status,`${r.orderedQuantity} / ${r.receivedQuantity} / ${r.outstandingQuantity}`,r.expectedAt?new Date(r.expectedAt).toLocaleDateString("fr-CA"):"Non renseigné",r.overdue?"EN RETARD":"Ouvert"])}/></div>
  <div><h3 className="mb-2 text-lg font-bold">Mouvements récents</h3><Table headers={["Date","Type","Identité","Delta","Source → destination","Référence","Auteur / groupe"]} rows={data.movements.rows.map((r:any)=>[new Date(r.movementDate).toLocaleString("fr-CA"),`${r.movementType} · ${r.classification}`,`${r.sku} · ${r.type}`,`${r.quantityDelta>0?"+":""}${r.quantityDelta} ${r.balanceField}`,`${r.sourceCode||"—"} → ${r.destinationCode||"—"}`,r.referenceType?`${r.referenceType} ${r.referenceId||""}`:"—",`${r.author} · ${r.groupId}`])}/></div>
  <div className="flex justify-between text-xs text-muted-foreground"><span>Généré le {new Date(data.generatedAt).toLocaleString("fr-CA")} · seuils: bas ≤ {data.thresholds.lowStockThreshold}, dormant {data.thresholds.dormantDays}j, lot ancien {data.thresholds.oldLotDays}j.</span><div><button disabled={!filters.offset} onClick={()=>setFilters((c:any)=>({...c,offset:Math.max(0,c.offset-25)}))} className="mr-2 rounded border px-2 py-1">Précédent</button><button onClick={()=>setFilters((c:any)=>({...c,offset:c.offset+25}))} className="rounded border px-2 py-1">Suivant</button></div></div></>}</section>;
}
