/**
 * CitiCigars business ID conventions (see project ID_CONVENTIONS.md):
 *   Customers  -> CTCG-CUST-XXXXXX   (CTCG-CUST-000000 reserved for CitiCigars itself)
 *   Sales      -> CTCG-SALE-XXXXXX   (the Master Gestion code IS orders.order_id — no parallel sequence)
 *   Suppliers  -> CTCG-SUPP-XXXXXX   (Phase 2)
 *   Followups  -> CTCG-FUP-XXXXXX
 *   DNA        -> CTCG-DNA-XXXXXX
 *   Line items / components are derived, deterministic handles from the
 *   sale id (CTCG-SALE-000014-L01, CTCG-SALE-000004-L01-C01) — NOT
 *   generated by this module, they come directly from the source data or
 *   from deterministic construction in the import code.
 *
 * No business-facing UUIDs. crypto.randomUUID() is no longer used for
 * customers/orders/followups/dna — only (if ever needed) for purely
 * internal, non-business-facing identifiers.
 */

export type CtcgPrefix = "CUST" | "SALE" | "SUPP" | "FUP" | "DNA";

/**
 * Formats a sequence number into a CTCG-<PREFIX>-XXXXXX id.
 * Does NOT allocate the sequence number itself — see nextSequence() below
 * for that, which must run against the real table to avoid collisions.
 */
export function formatCtcgId(prefix: CtcgPrefix, sequence: number): string {
  if (sequence < 0 || !Number.isInteger(sequence)) {
    throw new Error(`formatCtcgId: sequence must be a non-negative integer, got ${sequence}`);
  }
  return `CTCG-${prefix}-${String(sequence).padStart(6, "0")}`;
}

/**
 * Parses a CTCG id back into its prefix and numeric sequence. Used to find
 * the current max sequence in a table before allocating the next one.
 */
export function parseCtcgId(id: string): { prefix: string; sequence: number } | null {
  const match = /^CTCG-([A-Z]+)-(\d{6})$/.exec(id);
  if (!match) return null;
  return { prefix: match[1], sequence: parseInt(match[2], 10) };
}

/**
 * Given a list of existing CTCG ids for one prefix (as already stored in
 * the DB), returns the next sequence number. IDs are never reused or
 * renumbered (ID_CONVENTIONS.md) — this always looks at the true max, not
 * a count, so a manually excluded/deleted id never gets reassigned.
 */
export function nextSequenceFromExisting(existingIds: string[]): number {
  let max = -1;
  for (const id of existingIds) {
    const parsed = parseCtcgId(id);
    if (parsed && parsed.sequence > max) max = parsed.sequence;
  }
  return max + 1;
}

/** Deterministic line-item id derived from a sale id — not a new business code. */
export function formatOrderItemId(orderId: string, lineNumber: number): string {
  return `${orderId}-L${String(lineNumber).padStart(2, "0")}`;
}

/** Deterministic component snapshot id derived from an order item id. */
export function formatOrderItemComponentId(orderItemId: string, componentNumber: number): string {
  return `${orderItemId}-C${String(componentNumber).padStart(2, "0")}`;
}
