import { mysqlPool } from "../db.mysql";
import { balanceOf, evaluateIdentity, isOverdue, movementClass, parseMonitoringQuery } from "./stock-monitoring-model";

const key = (row: any) => `${row.sku}\u0000${row.type}\u0000${row.pack_size}`;
const fields = ["on_hand_qty", "reserved_client_qty", "reserved_event_qty", "at_event_qty", "deposit_qty", "transit_qty"];
const sumRows = (rows: any[]) => Object.fromEntries(fields.map((field) => [field, rows.reduce((sum, row) => sum + Number(row[field] || 0), 0)]));
const same = (left: any, right: any) => fields.every((field) => Number(left[field] || 0) === Number(right[field] || 0));
const page = (rows: any[], offset: number, limit: number) => ({ total: rows.length, limit, offset, rows: rows.slice(offset, offset + limit) });

export async function getStockMonitoring(rawQuery: Record<string, unknown>, now = new Date()) {
  const query = parseMonitoringQuery(rawQuery);
  const [aggregateRows] = await mysqlPool.query<any[]>(`SELECT b.*, p.marque, p.ligne, p.vitole, p.in_catalogue, p.availability_status FROM stock_balances b LEFT JOIN products p ON p.sku=b.sku`);
  const [locationRows] = await mysqlPool.query<any[]>(`SELECT b.*, l.code location_code, l.name location_name, l.category, l.active, l.is_system FROM stock_location_balances b JOIN stock_locations l ON l.location_id=b.location_id`);
  const [lotRows] = await mysqlPool.query<any[]>(`SELECT b.*, l.code location_code, l.name location_name, pl.lot_code, pl.origin_kind, r.receipt_code, r.received_at, s.supplier_id, s.code supplier_code, s.name supplier_name FROM stock_lot_location_balances b JOIN stock_locations l ON l.location_id=b.location_id JOIN stock_provenance_lots pl ON pl.lot_id=b.lot_id LEFT JOIN stock_receipts r ON r.receipt_id=pl.receipt_id LEFT JOIN stock_suppliers s ON s.supplier_id=r.supplier_id`);
  const [statsRows] = await mysqlPool.query<any[]>(`SELECT m.sku,m.type,m.pack_size,MIN(COALESCE(g.movement_date,g.created_at)) history_since,MAX(CASE WHEN g.movement_type='VENTE' THEN COALESCE(g.movement_date,g.created_at) END) last_sale_at,MAX(CASE WHEN g.movement_type='RECEPTION' THEN COALESCE(g.movement_date,g.created_at) END) last_inbound_at,MAX(COALESCE(g.movement_date,g.created_at)) last_movement_at,SUM(CASE WHEN g.movement_type='VENTE' AND m.balance_field='onHand' AND COALESCE(g.movement_date,g.created_at)>=DATE_SUB(?,INTERVAL 30 DAY) THEN ABS(m.qty_delta) ELSE 0 END) sold_30,SUM(CASE WHEN g.movement_type='VENTE' AND m.balance_field='onHand' AND COALESCE(g.movement_date,g.created_at)>=DATE_SUB(?,INTERVAL 60 DAY) THEN ABS(m.qty_delta) ELSE 0 END) sold_60,SUM(CASE WHEN g.movement_type='VENTE' AND m.balance_field='onHand' AND COALESCE(g.movement_date,g.created_at)>=DATE_SUB(?,INTERVAL 90 DAY) THEN ABS(m.qty_delta) ELSE 0 END) sold_90 FROM stock_movements m JOIN stock_movement_groups g ON g.group_id=m.group_id GROUP BY m.sku,m.type,m.pack_size`, [now, now, now]);
  const byLocation = new Map<string, any[]>(); const byLot = new Map<string, any[]>();
  for (const row of locationRows) byLocation.set(key(row), [...(byLocation.get(key(row)) || []), row]);
  for (const row of lotRows) byLot.set(key(row), [...(byLot.get(key(row)) || []), row]);
  const stats = new Map(statsRows.map((row) => [key(row), row]));
  let positions = aggregateRows.map((row) => {
    const locations = byLocation.get(key(row)) || []; const lots = byLot.get(key(row)) || [];
    const balance = balanceOf(row); const stat: any = stats.get(key(row)) || {};
    const reconciled = same(row, sumRows(locations)) && locations.every((location) => same(location, sumRows(lots.filter((lot) => lot.location_id === location.location_id))));
    const position: any = { sku: row.sku, type: row.type, packSize: Number(row.pack_size), label: [row.marque, row.ligne, row.vitole].filter(Boolean).join(" · ") || row.sku, ...balance, reconciled, legacyUnknown: lots.some((lot) => lot.origin_kind === "LEGACY_UNKNOWN" && balanceOf(lot).physicalUnits > 0), historySince: stat.history_since, lastSaleAt: stat.last_sale_at, lastInboundAt: stat.last_inbound_at, lastMovementAt: stat.last_movement_at, sold30: Number(stat.sold_30 || 0), sold60: Number(stat.sold_60 || 0), sold90: Number(stat.sold_90 || 0), catalogSellable: row.in_catalogue !== 0 && row.availability_status !== "DISCONTINUED" };
    position.alerts = evaluateIdentity(position, now, query);
    return position;
  });
  if (query.search) { const needle = query.search.toLocaleLowerCase(); positions = positions.filter((row) => `${row.sku} ${row.label}`.toLocaleLowerCase().includes(needle)); }

  const trusted = positions.filter((row) => row.reconciled); const bucketTotal = (name: string) => trusted.reduce((sum, row) => sum + row.buckets[name], 0);
  const summary = { activeIdentities: trusted.filter((row) => row.physicalUnits > 0).length, trustedIdentities: trusted.length, physicalStockUnits: trusted.reduce((sum, row) => sum + row.physicalUnits, 0), availableStockUnits: trusted.reduce((sum, row) => sum + row.availableNow, 0), reservedClient: bucketTotal("reservedClient"), reservedEvent: bucketTotal("reservedEvent"), atEvent: bucketTotal("atEvent"), deposit: bucketTotal("deposit"), transit: bucketTotal("transit"), zeroPositions: trusted.filter((row) => row.physicalUnits === 0).length, inconsistentIdentities: positions.length - trusted.length };

  const [poLineRows] = await mysqlPool.query<any[]>(`SELECT po.purchase_order_id,po.purchase_order_code,po.status,po.ordered_at,po.expected_at,po.purchase_reference,s.supplier_id,s.code supplier_code,s.name supplier_name,poi.purchase_order_item_id,poi.sku,poi.type,poi.pack_size,poi.ordered_quantity,COALESCE(SUM(ri.quantity),0) received_quantity FROM stock_purchase_orders po JOIN stock_suppliers s ON s.supplier_id=po.supplier_id JOIN stock_purchase_order_items poi ON poi.purchase_order_id=po.purchase_order_id LEFT JOIN stock_receipt_items ri ON ri.purchase_order_item_id=poi.purchase_order_item_id GROUP BY po.purchase_order_id,poi.purchase_order_item_id`);
  const poMap = new Map<string, any>();
  for (const row of poLineRows) { let order = poMap.get(row.purchase_order_id); if (!order) { order = { purchaseOrderId: row.purchase_order_id, purchaseOrderCode: row.purchase_order_code, status: row.status, orderedAt: row.ordered_at, expectedAt: row.expected_at, purchaseReference: row.purchase_reference, supplierId: row.supplier_id, supplierCode: row.supplier_code, supplierName: row.supplier_name, lines: [] }; poMap.set(row.purchase_order_id, order); } order.lines.push({ sku: row.sku, type: row.type, packSize: Number(row.pack_size), orderedQuantity: Number(row.ordered_quantity), receivedQuantity: Number(row.received_quantity), outstandingQuantity: Number(row.ordered_quantity) - Number(row.received_quantity) }); }
  let purchaseOrders = Array.from(poMap.values()).map((order) => ({ ...order, orderedQuantity: order.lines.reduce((s: number, r: any) => s + r.orderedQuantity, 0), receivedQuantity: order.lines.reduce((s: number, r: any) => s + r.receivedQuantity, 0), outstandingQuantity: order.lines.reduce((s: number, r: any) => s + r.outstandingQuantity, 0), overdue: isOverdue(order.expectedAt, order.status, now, query.poOverdueGraceDays) })).filter((order) => ["ORDERED", "PARTIALLY_RECEIVED"].includes(order.status));
  if (query.poStatus) purchaseOrders = purchaseOrders.filter((row) => row.status === query.poStatus);
  if (query.supplierId) purchaseOrders = purchaseOrders.filter((row) => row.supplierId === query.supplierId);
  (summary as any).openPurchaseOrders = purchaseOrders.length; (summary as any).overduePurchaseOrders = purchaseOrders.filter((row) => row.overdue).length;

  let alerts = positions.flatMap((position) => position.alerts.map((alert: any) => ({ ...alert, identity: { sku: position.sku, type: position.type, packSize: position.packSize }, label: position.label, availableNow: position.reconciled ? position.availableNow : null }))).concat(purchaseOrders.filter((order) => order.overdue).map((order) => ({ type: "OVERDUE_PO", severity: "ATTENTION", purchaseOrderId: order.purchaseOrderId, label: `${order.purchaseOrderCode} · ${order.supplierName}`, availableNow: null })));
  if (query.alertType) alerts = alerts.filter((row) => row.type === query.alertType);
  const severity = { CRITICAL: 0, ATTENTION: 1, WATCH: 2 } as any; alerts.sort((a, b) => severity[a.severity] - severity[b.severity] || a.label.localeCompare(b.label));

  const locationSummaries = Array.from(new Map(locationRows.map((row) => [row.location_id, row])).values()).map((location) => {
    const rows = locationRows.filter((row) => row.location_id === location.location_id); const trustworthyRows = rows.filter((row) => positions.find((p) => key({ sku: p.sku, type: p.type, pack_size: p.packSize }) === key(row))?.reconciled); const total = balanceOf(sumRows(trustworthyRows));
    return { locationId: location.location_id, code: location.location_code, name: location.location_name, category: location.category, activePositions: trustworthyRows.filter((row) => balanceOf(row).physicalUnits > 0).length, ...total, inconsistentIdentities: rows.length - trustworthyRows.length, legacyUnknownExposure: lotRows.some((lot) => lot.location_id === location.location_id && lot.origin_kind === "LEGACY_UNKNOWN" && balanceOf(lot).physicalUnits > 0) };
  }).sort((a, b) => a.code.localeCompare(b.code));

  let lots = lotRows.map((row) => ({ lotId: row.lot_id, lotCode: row.lot_code, originKind: row.origin_kind, sku: row.sku, type: row.type, packSize: Number(row.pack_size), locationId: row.location_id, locationCode: row.location_code, locationName: row.location_name, receiptCode: row.receipt_code, receivedAt: row.received_at, supplierId: row.supplier_id, supplierCode: row.supplier_code, supplierName: row.supplier_name, ...balanceOf(row), lotAgeDays: row.received_at ? Math.floor((now.getTime() - new Date(row.received_at).getTime()) / 86_400_000) : null })).filter((row) => row.physicalUnits > 0);
  if (query.locationId) lots = lots.filter((row) => row.locationId === query.locationId); if (query.supplierId) lots = lots.filter((row) => row.supplierId === query.supplierId);
  lots.sort((a, b) => (b.lotAgeDays ?? -1) - (a.lotAgeDays ?? -1) || a.lotCode.localeCompare(b.lotCode));

  const clauses: string[] = []; const params: any[] = [];
  if (query.search) { clauses.push("(m.sku LIKE ? OR p.marque LIKE ? OR p.ligne LIKE ? OR p.vitole LIKE ?)"); for (let i=0;i<4;i++) params.push(`%${query.search}%`); }
  if (query.locationId) { clauses.push("(g.source_location_id=? OR g.destination_location_id=?)"); params.push(query.locationId, query.locationId); }
  if (query.movementType) { clauses.push("g.movement_type=?"); params.push(query.movementType); }
  if (query.referenceType) { clauses.push("g.reference_type=?"); params.push(query.referenceType); }
  const where = clauses.length ? `WHERE ${clauses.join(" AND ")}` : "";
  const [movementCount] = await mysqlPool.query<any[]>(`SELECT COUNT(*) total FROM stock_movements m JOIN stock_movement_groups g ON g.group_id=m.group_id LEFT JOIN products p ON p.sku=m.sku ${where}`, params);
  const [movementRows] = await mysqlPool.query<any[]>(`SELECT m.id,m.sku,m.type,m.pack_size,m.balance_field,m.qty_delta,g.group_id,g.movement_type,g.reference_type,g.reference_id,g.author,COALESCE(g.movement_date,g.created_at) movement_date,sl.code source_code,dl.code destination_code FROM stock_movements m JOIN stock_movement_groups g ON g.group_id=m.group_id LEFT JOIN products p ON p.sku=m.sku LEFT JOIN stock_locations sl ON sl.location_id=g.source_location_id LEFT JOIN stock_locations dl ON dl.location_id=g.destination_location_id ${where} ORDER BY COALESCE(g.movement_date,g.created_at) DESC,g.created_at DESC,m.id DESC LIMIT ? OFFSET ?`, [...params, query.limit, query.offset]);
  const movements = { total: Number(movementCount[0]?.total || 0), limit: query.limit, offset: query.offset, rows: movementRows.map((row) => ({ id: row.id, groupId: row.group_id, movementDate: row.movement_date, movementType: row.movement_type, classification: movementClass(row.movement_type, Number(row.qty_delta)), sku: row.sku, type: row.type, packSize: Number(row.pack_size), balanceField: row.balance_field, quantityDelta: Number(row.qty_delta), sourceCode: row.source_code, destinationCode: row.destination_code, referenceType: row.reference_type, referenceId: row.reference_id, author: row.author })) };
  const commercial = positions.filter((row) => row.catalogSellable).sort((a,b) => b.availableNow-a.availableNow || a.sku.localeCompare(b.sku));
  return { generatedAt: now.toISOString(), readOnly: true, unitWarning: "Totals are stock units across distinct Box, Pack, Loose, and Accessory identities; they are not a cigar count.", historyPolicy: "Dormant means available stock with no VENTE during the configured period only when this identity's observed ledger starts before that period; otherwise history is insufficient.", thresholds: { lowStockThreshold: query.lowStockThreshold, dormantDays: query.dormantDays, oldLotDays: query.oldLotDays, poOverdueGraceDays: query.poOverdueGraceDays }, summary, alerts: page(alerts, query.offset, query.limit), commercial: page(commercial, query.offset, query.limit), dormant: page(positions.filter((row) => row.availableNow > 0 && (row.dormant || !row.historySufficient)), query.offset, query.limit), locations: locationSummaries, lots: page(lots, query.offset, query.limit), purchasing: page(purchaseOrders, query.offset, query.limit), movements };
}
